import 'package:ecommerce_store/utils/product_model.dart';

final List<ProductModel> products = [
  ProductModel(
    id: '1',
    name: 'Apple MacBook Pro 14"',
    description: 'M2 Pro chip, 16GB RAM, 512GB SSD',
    price: 1999.99,
    image1: 'assets/products/macbook_air.png',
    image2: 'assets/products/macbook_air.png',
    image3: 'assets/products/macbook_air.png',
    type: 'Laptop',
    colorOptions: ['Space Gray', 'Silver'],
    rating: 4.8,
  ),
  ProductModel(
    id: '2',
    name: 'Dell Inspiron 15',
    description: 'Intel i7, 16GB RAM, 1TB HDD',
    price: 899.99,
    image1: 'assets/products/dell_laptop.png',
    image2: 'assets/products/macbook_air.png',
    image3: null,
    type: 'Laptop',
    colorOptions: ['Black', 'Silver'],
    rating: 4.3,
  ),
  ProductModel(
    id: '3',
    name: 'Sony WH-1000XM5',
    description: 'Noise Cancelling Wireless Headphones',
    price: 349.99,
    image1: 'assets/products/headphone.png',
    image2: 'assets/products/headphone1.png',
    image3: null,
    type: 'Headset',
    colorOptions: ['Black', 'White'],
    rating: 4.7,
  ),
  ProductModel(
    id: '4',
    name: 'JBL Quantum 800',
    description: 'Gaming Wireless Headset with RGB lighting',
    price: 199.99,
    image1: 'assets/products/headphone2.png',
    image2: 'assets/products/headphone3.png',
    image3: 'assets/products/headphone2.png',
    type: 'Headset',
    colorOptions: ['Black', 'Red'],
    rating: 4.2,
  ),
  ProductModel(
    id: '5',
    name: 'Samsung Galaxy Buds2 Pro',
    description: 'High-quality wireless earbuds',
    price: 229.99,
    image1: 'assets/products/samsung_buds.png',
    image2: 'assets/products/samsung_buds2.png',
    image3: null,
    type: 'Buds',
    colorOptions: ['Graphite', 'White', 'Bora Purple'],
    rating: 4.5,
  ),
  ProductModel(
    id: '6',
    name: 'Apple AirPods Pro',
    description: '2nd generation with improved ANC',
    price: 249.99,
    image1: 'assets/products/airpods.png',
    image2: 'assets/products/airpods.png',
    image3: null,
    type: 'Buds',
    colorOptions: ['White'],
    rating: 4.6,
  ),
  ProductModel(
    id: '7',
    name: 'Nike Running Shoes',
    description: 'Lightweight shoes for daily runs',
    price: 119.99,
    image1: 'assets/products/running_shoes.png',
    image2: 'assets/products/running_shoes.png',
    image3: 'assets/products/nike_shoes.png',
    type: 'Sports',
    colorOptions: ['Black', 'Blue', 'Red'],
    rating: 4.4,
  ),
  ProductModel(
    id: '8',
    name: 'Adidas Soccer Ball',
    description: 'FIFA approved match ball',
    price: 39.99,
    image1: 'assets/products/adidas_ball.png',
    image2: null,
    image3: null,
    type: 'Sports',
    colorOptions: ['White/Black', 'Orange'],
    rating: 4.1,
  ),
  ProductModel(
    id: '9',
    name: 'Men\'s Casual T-Shirt',
    description: 'Comfortable cotton T-shirt',
    price: 19.99,
    image1: 'https://example.com/tshirt_main.png',
    image2: 'https://example.com/tshirt_back.png',
    image3: null,
    type: 'Fashion',
    colorOptions: ['Black', 'White', 'Navy Blue'],
    rating: 4.3,
  ),
  ProductModel(
    id: '10',
    name: 'Women\'s Handbag',
    description: 'Stylish leather handbag',
    price: 89.99,
    image1: 'https://example.com/handbag_main.png',
    image2: 'https://example.com/handbag_inside.png',
    image3: 'https://example.com/handbag_side.png',
    type: 'Fashion',
    colorOptions: ['Brown', 'Black', 'Red'],
    rating: 4.5,
  ),
  ProductModel(
    id: '11',
    name: 'Pack of Organic Rice',
    description: '5kg pack of organic basmati rice',
    price: 15.99,
    image1: 'https://example.com/rice_main.png',
    image2: null,
    image3: null,
    type: 'Supermarket',
    colorOptions: ['N/A'],
    rating: 4.0,
  ),
  ProductModel(
    id: '12',
    name: 'Olive Oil 1L',
    description: 'Extra virgin olive oil',
    price: 9.99,
    image1: 'https://example.com/oil_main.png',
    image2: null,
    image3: null,
    type: 'Supermarket',
    colorOptions: ['N/A'],
    rating: 4.2,
  ),
  ProductModel(
    id: '13',
    name: 'Breakfast Cereal',
    description: 'Healthy multigrain cereal',
    price: 4.99,
    image1: 'https://example.com/cereal_main.png',
    image2: 'https://example.com/cereal_box.png',
    image3: null,
    type: 'Supermarket',
    colorOptions: ['N/A'],
    rating: 4.1,
  ),
];

List<String> getTypesList(List<ProductModel> list) {
  return list.map((p) => p.type).toSet().toList();
}

final productTypes = getTypesList(products);
